// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoriesController from "./categories_controller"
application.register("categories", CategoriesController)

import GameInputController from "./game_input_controller"
application.register("game-input", GameInputController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
